### Buscar todos os carros
GET http://localhost:3000/api/v1/carros
### Buscar carro pelo ID
GET http://localhost:3000/api/v1/carros/3f840c63-130c-436b-8543-97ab14caf16f

### Inserir um novo Carro
POST http://localhost:3000/api/v1/carros
Content-Type: application/json

{
  "placa": "MDB3389"
}

### Atualizar o  Carro
PUT http://localhost:3000/api/v1/carros/bed1c3ec-fd13-433e-986f-c23419a9cdf9
Content-Type: application/json

{
  "placa": "MAS1334-2"
}

### Remover o Carro
DELETE  http://localhost:3000/api/v1/carros/bed1c3ec-fd13-433e-986f-c23419a9cdf9
Content-Type: application/json